# Generated by Django 3.2.4 on 2024-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('navbar_logo', models.FileField(blank=True, null=True, upload_to='_fs/static/')),
                ('login_logo', models.FileField(blank=True, null=True, upload_to='_fs/static/')),
            ],
        ),
    ]
