# Generated by Django 3.2.4 on 2024-03-11 10:04

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(max_length=255, unique=True)),
                ('signature', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('task_type', models.IntegerField(choices=[(1, 'DATA_EXPORT'), (2, 'DATA_IMPORT'), (3, 'G_PHASE'), (4, 'OCPMDM'), (5, 'CERTIFICATE'), (6, 'EXPORT_FOR_CERTIFICATE'), (7, 'DATA_IMPORT_VERIFY'), (8, 'UPLOAD_HISTORY_REVIEW_REVOKE'), (9, 'UPLOAD_HISTORY_RETRACT'), (9999, 'GENERIC_SYSTEM'), (10000, 'ES_IMPORT'), (10001, 'IMAGE_SEARCH_FEATURE_GENERATE'), (10002, 'CERTIFICATE_UPDATE'), (10003, 'CERTIFICATE_REBUILD'), (10004, 'CERTIFICATE_REBUILD_FULL')])),
                ('exc', models.BinaryField(null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILED'), ('REVOKED', 'CANCELLED'), ('DELETED', 'DELETED')], default='PENDING', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
