# Generated by Django 3.2.4 on 2024-07-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slave', '0002_alter_ophistory_op_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ophistory',
            name='op_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ADD_DATA'), (2, 'MODIFY_DATA'), (3, 'DELETE_DATA')], db_index=True),
        ),
    ]
