debug_subject_quotas = [
    {'id': '11',
     'indexKey': None,
     'indexName': '三、专著人才等情况',
     'reference': '0',
     'parentId': '0',
     'isText': '0',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '1',
     'yjwcl': '0',
     'sjwcl': None,
     'isCheck': None},
    {'id': '12',
     'indexKey': None,
     'indexName': '毕业研究生数',
     'reference': '3',
     'parentId': '11',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '8',
     'sjwcl': None,
     'isCheck': None},
    {'id': '15',
     'indexKey': None,
     'indexName': '四、新理论、新技术、新产品等情况',
     'reference': '0',
     'parentId': '0',
     'isText': '0',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '1',
     'yjwcl': '0',
     'sjwcl': None,
     'isCheck': None},
    {'id': '4b314a5fc99a471287503c75cbbf899e',
     'indexKey': None,
     'indexName': '技术指标3-制备梯度合金尺寸≥Φ5×500mm',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '4dc3149212cc45508e36465b7a94861c',
     'indexKey': None,
     'indexName': '技术指标4-样品组元数≥4，溶质组元的成分0~50%变化，连续变化',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '74dc6dd12c124121bc5c824d80b059a1',
     'indexKey': None,
     'indexName': '技术指标5-制备合金可测性能：硬度、细胞毒性、耐蚀性',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '978fb098150f4b7496a7472e258a808c',
     'indexKey': None,
     'indexName': '技术指标1-全自动控制，包括连续调节加料、梯度升温、螺旋推进、结晶凝固及引锭拉出，全部由程序控制',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': 'bfabb6a034cf49a18c28a0ec3af38ae8',
     'indexKey': None,
     'indexName': '技术指标2-可控温度梯度≥200℃',
     'reference': '5',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': 'eb69ee50f32146768b39221c29137d82',
     'indexKey': None,
     'indexName': '应用指标-制备四元以上镁、锌合金成分连续梯度变化棒材',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '30',
     'indexKey': None,
     'indexName': '七、论文发表情况',
     'reference': '0',
     'parentId': '0',
     'isText': '0',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '1',
     'yjwcl': '0',
     'sjwcl': None,
     'isCheck': None},
    {'id': '32',
     'indexKey': None,
     'indexName': '发表（Sci/Ei）',
     'reference': '3',
     'parentId': '30',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '12',
     'sjwcl': None,
     'isCheck': None},
    {'id': '6',
     'indexKey': None,
     'indexName': '二、专利情况',
     'reference': '0',
     'parentId': '0',
     'isText': '0',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '1',
     'yjwcl': '0',
     'sjwcl': None,
     'isCheck': None},
    {'id': '7',
     'indexKey': None,
     'indexName': '申请发明专利项数',
     'reference': '3',
     'parentId': '6',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '3',
     'sjwcl': None,
     'isCheck': None}]

debug_project_quotas = [
    {'id': '6',
     'indexKey': None,
     'indexName': '二、专利情况',
     'reference': '0',
     'parentId': '0',
     'isText': '0',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '1',
     'yjwcl': '0',
     'sjwcl': None,
     'isCheck': None},
    {'id': '7',
     'indexKey': None,
     'indexName': '申请发明专利项数',
     'reference': '15',
     'parentId': '6',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '26',
     'sjwcl': None,
     'isCheck': None},
    {'id': '11',
     'indexKey': None,
     'indexName': '三、专著人才等情况',
     'reference': '0',
     'parentId': '0',
     'isText': '0',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '1',
     'yjwcl': '0',
     'sjwcl': None,
     'isCheck': None},
    {'id': '12',
     'indexKey': None,
     'indexName': '毕业研究生数',
     'reference': '15',
     'parentId': '11',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '35',
     'sjwcl': None,
     'isCheck': None},
    {'id': '15',
     'indexKey': None,
     'indexName': '四、新理论、新技术、新产品等情况',
     'reference': '0',
     'parentId': '0',
     'isText': '0',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '1',
     'yjwcl': '0',
     'sjwcl': None,
     'isCheck': None},
    {'id': '0c8a80d6a07648089cb75de018b5af1e',
     'indexKey': None,
     'indexName': '多组元粉末布料装置：组元数≥6；布料均匀性：元素添加量≤2%，混料均匀性±10%；元素添加量>2%，混料均匀性±5%',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '12c812d6b24f4f8a867da75e1e880b36',
     'indexKey': None,
     'indexName': '新技术：可在线检测熔池界面状态，缺陷的空间分辨率≤0.3mm。',
     'reference': '3',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '1af87fe6336d43548dfdf01c939a2fb1',
     'indexKey': None,
     'indexName': '梯度热变形处理技术高通量制备微观组织梯度变化的块体材料，结合高通量表征，高效获取变形工艺-组织-性能相互关系。',
     'reference': '5',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '1b087a940ef94401a99b1f957eaf7466',
     'indexKey': None,
     'indexName': '应用指标（形成低熔点玻璃、高导热陶瓷高通量制备及性能优选示范）',
     'reference': '3',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '222fee37d9394b27ab531995f4dc8770',
     'indexKey': None,
     'indexName': '新装置（同步合成三组分梯度变化样品单元数≥100，单个样品尺寸≥10×10×5mm，单一块体内成分偏差≤1wt%）',
     'reference': '3',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '3ebea427f50347fa8e211fa5835868d7',
     'indexKey': None,
     'indexName': '采用粉末冶金标准抗弯试样35×5×5mm3进行测试评价',
     'reference': '5',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '4a996b206434480aa25bf6019850b2b4',
     'indexKey': None,
     'indexName': '同步合成分立组分块体样品100个以上；多温区梯度烧结炉：温度段数量≥8 段，每段等温区40-80mm，每段温度均匀性±5℃',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '4b314a5fc99a471287503c75cbbf899e',
     'indexKey': None,
     'indexName': '技术指标3-制备梯度合金尺寸≥Φ5×500mm',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '4cc7749c0d60400a9021b03965ccb6a3',
     'indexKey': None,
     'indexName': '温度准确调控，形成可靠高通量材料制备方法，同步合成可检测的微区样品单元≥100个，表征关键性能:硬度、晶格常数、热导率。',
     'reference': '5',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '4dc3149212cc45508e36465b7a94861c',
     'indexKey': None,
     'indexName': '技术指标4-样品组元数≥4，溶质组元的成分0~50%变化，连续变化',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    # {'id': '5dba95206e0b4c93bffd5193f97c6a26',
    #  'indexKey': None,
    #  'indexName': '高温合金梯度微观组织的高通量制备及其组织与性能的高通量表征。以传统的高温合金热处理制备方法(包括材料准备、装炉、抽真空、加热升温、保温、一个试样一个冷却速率、制样)的速度和费用为基准，基于梯度热机械处理的高通量合金制备的速度提高倍数与费用降低倍数比值≥10。',
    #  'reference': '5',
    #  'parentId': '15',
    #  'isText': '1',
    #  'level': None,
    #  'projectId': None,
    #  'topicId': None,
    #  'cctCreate': None,
    #  'del': None,
    #  'codeLevel': '2',
    #  'yjwcl': '1',
    #  'sjwcl': None,
    #  'isCheck': None},
    # {'id': '74dc6dd12c124121bc5c824d80b059a1',
    #  'indexKey': None,
    #  'indexName': '技术指标5-制备合金可测性能：硬度、细胞毒性、耐蚀性',
    #  'reference': '15',
    #  'parentId': '15',
    #  'isText': '1',
    #  'level': None,
    #  'projectId': None,
    #  'topicId': None,
    #  'cctCreate': None,
    #  'del': None,
    #  'codeLevel': '2',
    #  'yjwcl': '1',
    #  'sjwcl': None,
    #  'isCheck': None},
    # {'id': '81a96a5132224d2c8ff121da1c110374',
    #  'indexKey': None,
    #  'indexName': '高通量装置：4通道4组元材料送进；同步合成样品数不低于100 个，成分动态调控；集成质量检测系统的激光增材制造高通量块体材料的装备，无故障运行时间大于200小时，批次稳定性优于10%。',
    #  'reference': '3',
    #  'parentId': '15',
    #  'isText': '1',
    #  'level': None,
    #  'projectId': None,
    #  'topicId': None,
    #  'cctCreate': None,
    #  'del': None,
    #  'codeLevel': '2',
    #  'yjwcl': '2',
    #  'sjwcl': None,
    #  'isCheck': None},
    # {'id': '82013b43cbd04bf1bb114a9f07e4368d',
    #  'indexKey': None,
    #  'indexName': '应用指标：实现钛基和镍基合金的块体材料高能束增材高通量制备应用，和传统相比，加工速度提高倍数与费用降低倍数比值≥10，实现至少三种性能的快速检测，误差＜10%。',
    #  'reference': '3',
    #  'parentId': '15',
    #  'isText': '1',
    #  'level': None,
    #  'projectId': None,
    #  'topicId': None,
    #  'cctCreate': None,
    #  'del': None,
    #  'codeLevel': '2',
    #  'yjwcl': '1',
    #  'sjwcl': None,
    #  'isCheck': None},
    # {'id': '978fb098150f4b7496a7472e258a808c',
    #  'indexKey': None,
    #  'indexName': '技术指标1-全自动控制，包括连续调节加料、梯度升温、螺旋推进、结晶凝固及引锭拉出，全部由程序控制',
    #  'reference': '15',
    #  'parentId': '15',
    #  'isText': '1',
    #  'level': None,
    #  'projectId': None,
    #  'topicId': None,
    #  'cctCreate': None,
    #  'del': None,
    #  'codeLevel': '2',
    #  'yjwcl': '1',
    #  'sjwcl': None,
    #  'isCheck': None},
    # {'id': 'bfabb6a034cf49a18c28a0ec3af38ae8',
    #  'indexKey': None,
    #  'indexName': '技术指标2-可控温度梯度≥200℃',
    #  'reference': '5',
    #  'parentId': '15',
    #  'isText': '1',
    #  'level': None,
    #  'projectId': None,
    #  'topicId': None,
    #  'cctCreate': None,
    #  'del': None,
    #  'codeLevel': '2',
    #  'yjwcl': '1',
    #  'sjwcl': None,
    #  'isCheck': None},
    # {'id': 'c0a808541d0249048e9fd4a3a565430c',
    #  'indexKey': None,
    #  'indexName': '实现粉末冶金高速钢块体材料高通量制备，以传统的粉末冶金高速钢块体材料制备方法（包括输送、混合、致密化等）的速度和费用为基准，基于粉末冶金高通量方法制备的速度提高倍数与费用降低倍数比值≥10',
    #  'reference': '15',
    #  'parentId': '15',
    #  'isText': '1',
    #  'level': None,
    #  'projectId': None,
    #  'topicId': None,
    #  'cctCreate': None,
    #  'del': None,
    #  'codeLevel': '2',
    #  'yjwcl': '1',
    #  'sjwcl': None,
    #  'isCheck': None},
    # {'id': 'c6f33283e0154aa7b52ec59ac181681a',
    #  'indexKey': None,
    #  'indexName': '端淬梯度热处理技术高通量制备微观组织梯度变化的块体材料，结合高通量表征，高效获取冷速-相-组织-性能相互关系。',
    #  'reference': '5',
    #  'parentId': '15',
    #  'isText': '1',
    #  'level': None,
    #  'projectId': None,
    #  'topicId': None,
    #  'cctCreate': None,
    #  'del': None,
    #  'codeLevel': '2',
    #  'yjwcl': '1',
    #  'sjwcl': None,
    #  'isCheck': None},
    # {'id': 'c908b819f3ff430989e49dc8d76f3254',
    #  'indexKey': None,
    #  'indexName': '研制蜂巢式热等静压多样品包套装置；同步合成分立组份块体样品100个以上',
    #  'reference': '15',
    #  'parentId': '15',
    #  'isText': '1',
    #  'level': None,
    #  'projectId': None,
    #  'topicId': None,
    #  'cctCreate': None,
    #  'del': None,
    #  'codeLevel': '2',
    #  'yjwcl': '1',
    #  'sjwcl': None,
    #  'isCheck': None},
    {'id': 'd8f792d676a7420086e2bbcfb9997041',
     'indexKey': None,
     'indexName': '基于单传感器差热分析相变温度检测方法，热模拟可靠预测试样温度场分布。',
     'reference': '5',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': 'e868342f583649388f652dc6c8ac38aa',
     'indexKey': None,
     'indexName': '新技术：4通道4组元材料送进，同步合成样品数不低于100 个，成分动态调控。',
     'reference': '3',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': 'eb69ee50f32146768b39221c29137d82',
     'indexKey': None,
     'indexName': '应用指标-制备四元以上镁、锌合金成分连续梯度变化棒材',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': 'ed848dad9eb2423883c89f82ab73a8fd',
     'indexKey': None,
     'indexName': '质量指标：集成质量检测系统的激光增材制造高通量块体材料的装备，无故障运行时间大于200小时，批次稳定性优于10%。',
     'reference': '3',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': 'f859765bdf624a26808d738a5f7ea0e5',
     'indexKey': None,
     'indexName': '同步混合粉末分立样品数达到100个，均匀性：单配方量>50g；元素添加量≤2%，混料均匀性±10%；元素添加量>2%，混料均匀性±5%',
     'reference': '15',
     'parentId': '15',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '1',
     'sjwcl': None,
     'isCheck': None},
    {'id': '30',
     'indexKey': None,
     'indexName': '七、论文发表情况',
     'reference': '0',
     'parentId': '0',
     'isText': '0',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '1',
     'yjwcl': '0',
     'sjwcl': None,
     'isCheck': None},
    {'id': '32',
     'indexKey': None,
     'indexName': '发表（Sci/Ei）',
     'reference': '6',
     'parentId': '30',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '24',
     'sjwcl': None,
     'isCheck': None},
    {'id': '33',
     'indexKey': None,
     'indexName': '提交数据到MGE平台的论文数量',
     'reference': '9',
     'parentId': '30',
     'isText': '1',
     'level': None,
     'projectId': None,
     'topicId': None,
     'cctCreate': None,
     'del': None,
     'codeLevel': '2',
     'yjwcl': '36',
     'sjwcl': None,
     'isCheck': None}]
