# Generated by Django 3.2.4 on 2024-03-15 05:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectsubjectmember',
            unique_together={('project', 'subject', 'user')},
        ),
    ]
