# Generated by Django 3.2.4 on 2024-03-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_projectsubjectmember_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacontentfile',
            name='hash_value',
        ),
        migrations.RemoveField(
            model_name='datacontentfile',
            name='real_file_id',
        ),
        migrations.RemoveField(
            model_name='datacontentfile',
            name='size',
        ),
        migrations.RemoveField(
            model_name='datacontentimage',
            name='hash_value',
        ),
        migrations.RemoveField(
            model_name='datacontentimage',
            name='real_file_id',
        ),
        migrations.RemoveField(
            model_name='datacontentimage',
            name='size',
        ),
        migrations.RemoveField(
            model_name='temporarydatatemplate',
            name='hash_value',
        ),
        migrations.RemoveField(
            model_name='temporarydatatemplate',
            name='real_file_id',
        ),
        migrations.RemoveField(
            model_name='temporarydatatemplate',
            name='size',
        ),
        migrations.RemoveField(
            model_name='temporaryexportedfile',
            name='hash_value',
        ),
        migrations.RemoveField(
            model_name='temporaryexportedfile',
            name='real_file_id',
        ),
        migrations.RemoveField(
            model_name='temporaryexportedfile',
            name='size',
        ),
        migrations.RemoveField(
            model_name='temporaryuploadedfile',
            name='hash_value',
        ),
        migrations.RemoveField(
            model_name='temporaryuploadedfile',
            name='real_file_id',
        ),
        migrations.RemoveField(
            model_name='temporaryuploadedfile',
            name='size',
        ),
    ]
