# Generated by Django 3.2.4 on 2024-03-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20240320_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacontentfile',
            name='hash_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='datacontentimage',
            name='hash_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='temporarydatatemplate',
            name='hash_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='temporaryexportedfile',
            name='hash_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='temporaryuploadedfile',
            name='hash_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
