# Generated by Django 3.2.4 on 2024-05-06 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, transaction


def create_batch_upload_history(apps, schema_editor):
    DataMeta = apps.get_model('storage', 'DataMeta')
    BatchUploadHistory = apps.get_model('storage', 'BatchUploadHistory')

    _map = {}
    for meta in DataMeta.objects.all().only('user', 'add_time', 'template_id'):
        key = (meta.user_id, meta.add_time.replace(minute=0, second=0, microsecond=0), meta.template_id)
        _map.setdefault(key, []).append(meta.id)
    with transaction.atomic():
        for (user_id, add_time, template_id), meta_ids in _map.items():
            batch = BatchUploadHistory.objects.create(user_id=user_id, created_at=add_time)
            DataMeta.objects.filter(id__in=meta_ids).update(batch_upload_history=batch)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0005_auto_20240320_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datameta',
            name='category',
            field=models.ForeignKey(limit_choices_to={'leaf': True}, null=True,
                                    on_delete=django.db.models.deletion.PROTECT, to='storage.category'),
        ),
        migrations.AlterField(
            model_name='datameta',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='reviewed_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datameta',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BatchUploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datameta',
            name='batch_upload_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='storage.batchuploadhistory'),
        ),
        migrations.RunPython(create_batch_upload_history),
    ]
