# Generated by Django 3.2.4 on 2024-06-06 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_auto_20240506_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='datameta',
            name='water_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastatistic',
            name='waterMark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialproject',
            name='waterMark',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='templatedatastatistic',
            name='day',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
