# Generated by Django 3.2.4 on 2024-06-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20240607_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
